import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "classification" model, go to https://office-wizard.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v2",
  storageKey: "ZVk5bYkU7uu4",
  comment:
    "AI classification and scoring results for emails. Stores intent analysis, priority calculations, automation recommendations, and extracted entities to help route and prioritize inbound messages. Created by classification system, read by support agents and managers.",
  fields: {
    ageFollowupsScore: {
      type: "number",
      default: 0,
      decimals: 1,
      validations: { numberRange: { min: 0, max: 3 } },
      storageKey: "9zk1hB6HatJ-",
      searchIndex: false,
    },
    automationConfidence: {
      type: "number",
      decimals: 2,
      validations: {
        required: true,
        numberRange: { min: 0, max: 1 },
      },
      storageKey: "4dWUkrPZ5oFc",
      searchIndex: false,
    },
    automationReason: {
      type: "string",
      storageKey: "YlYY6GS0zziN",
      filterIndex: false,
    },
    automationTag: {
      type: "enum",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: [
        "auto_reply",
        "auto_resolve",
        "human_required",
        "escalate",
      ],
      validations: { required: true },
      storageKey: "sCyrQARiWZ6W",
    },
    categoryBaseScore: {
      type: "number",
      decimals: 2,
      validations: { numberRange: { min: 0, max: 3 } },
      storageKey: "Qc52Wpzabb0Q",
      searchIndex: false,
    },
    classifiedAt: {
      type: "dateTime",
      includeTime: true,
      validations: { required: true },
      storageKey: "kG1W-rfUYcb2",
    },
    containsChargebackMention: {
      type: "boolean",
      default: false,
      storageKey: "6Zof20SmfbJz",
      searchIndex: false,
    },
    containsLegalThreat: {
      type: "boolean",
      default: false,
      storageKey: "dcHwfFAqrkQ3",
      searchIndex: false,
    },
    containsNegativeReview: {
      type: "boolean",
      default: false,
      storageKey: "jZ2uIcv3Sjtd",
      searchIndex: false,
    },
    conversation: {
      type: "belongsTo",
      validations: { required: true },
      parent: { model: "conversation" },
      storageKey: "MsQ6qvhG1xUW",
      searchIndex: false,
    },
    emailMessage: {
      type: "belongsTo",
      validations: { required: true },
      parent: { model: "emailMessage" },
      storageKey: "5K8Wwz96Hw0M",
      searchIndex: false,
    },
    emotionTags: { type: "json", storageKey: "jr9XzRBein9f" },
    escalationScore: {
      type: "number",
      default: 0,
      decimals: 2,
      validations: { numberRange: { min: 0, max: 3 } },
      storageKey: "VEWOeboGNEr6",
      searchIndex: false,
    },
    extractedCustomerName: {
      type: "string",
      storageKey: "8VyMFOvhcjf_",
    },
    extractedDeadlineDates: {
      type: "json",
      storageKey: "lpAxObJWMgdt",
      filterIndex: false,
      searchIndex: false,
    },
    extractedMoneyAmounts: {
      type: "json",
      storageKey: "6XzsWL6S0-U2",
      searchIndex: false,
    },
    extractedOrderId: { type: "string", storageKey: "diVaj9d4u5z6" },
    extractedProductNames: {
      type: "json",
      storageKey: "1U2aOQVvfdin",
      filterIndex: false,
    },
    hasAddressInfo: {
      type: "boolean",
      default: false,
      storageKey: "ahwCCXUdLVml",
      searchIndex: false,
    },
    intentCategory: {
      type: "enum",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: [
        "refund_cancellation",
        "complaint",
        "order_issue",
        "delivery_deadline",
        "technical_product_help",
        "presales_question",
        "general_question",
        "other",
      ],
      validations: { required: true },
      storageKey: "pGf-_zrqwIWI",
    },
    intentConfidence: {
      type: "number",
      decimals: 2,
      validations: {
        required: true,
        numberRange: { min: 0, max: 1 },
      },
      storageKey: "15eS7LomvIr8",
      searchIndex: false,
    },
    modelVersion: {
      type: "string",
      storageKey: "6LnJQnp4xhyy",
      searchIndex: false,
    },
    operationalBlockerScore: {
      type: "number",
      default: 0,
      decimals: 0,
      validations: { numberRange: { min: 0, max: 3 } },
      storageKey: "rj_WXa2rqtFW",
      searchIndex: false,
    },
    priorityBand: {
      type: "enum",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: ["P0", "P1", "P2", "P3"],
      validations: { required: true },
      storageKey: "gfS73PUl5jwZ",
      searchIndex: false,
    },
    priorityScore: {
      type: "number",
      decimals: 2,
      validations: {
        required: true,
        numberRange: { min: 0, max: null },
      },
      storageKey: "q2I7B2LWTpvb",
      searchIndex: false,
    },
    requiresRefund: {
      type: "boolean",
      default: false,
      storageKey: "sS_wxkWIF8bv",
      searchIndex: false,
    },
    riskChurnScore: {
      type: "number",
      default: 0,
      decimals: 2,
      validations: { numberRange: { min: 0, max: 3 } },
      storageKey: "HrYXTUjs2g4n",
      searchIndex: false,
    },
    scoringConfidence: {
      type: "enum",
      default: "medium",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: ["low", "medium", "high"],
      storageKey: "L5C1ZlJAvFIx",
    },
    scoringNotes: {
      type: "string",
      storageKey: "_iVCTOw2rm7U",
      filterIndex: false,
    },
    senderType: {
      type: "enum",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: [
        "customer",
        "supplier",
        "internal",
        "automated_system",
        "spam_marketing",
        "unknown",
      ],
      validations: { required: true },
      storageKey: "hjEwaF0hlOZE",
    },
    sentimentLabel: {
      type: "enum",
      default: "neutral",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: [
        "very_negative",
        "negative",
        "neutral",
        "positive",
        "very_positive",
      ],
      storageKey: "VHoQCkIBadKM",
    },
    sentimentScore: {
      type: "number",
      default: 0,
      decimals: 1,
      validations: { numberRange: { min: 0, max: 3 } },
      storageKey: "MUY2gwiYSw1B",
      searchIndex: false,
    },
    timeSensitivityScore: {
      type: "number",
      decimals: 1,
      validations: { numberRange: { min: 0, max: 3 } },
      storageKey: "uIHPxP-GozBP",
    },
    topDrivers: {
      type: "json",
      validations: { required: true },
      storageKey: "EpVkAMciTgEO",
      filterIndex: false,
    },
    valueBandScore: {
      type: "number",
      default: 0,
      decimals: 2,
      validations: { numberRange: { min: 0, max: 3 } },
      storageKey: "zMPnhKY_AQoU",
      searchIndex: false,
    },
  },
};
