import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "appConfiguration" model, go to https://office-wizard.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v2",
  storageKey: "5VpweQO0ZSDt",
  comment:
    "Stores system-wide configuration and settings for Email Wizard, including Microsoft Graph connection, default folders, triage settings, scoring configuration, and more.",
  fields: {
    ageWeightPointsPerDay: {
      type: "number",
      default: 2,
      decimals: 0,
      storageKey: "ageWeightPointsPerDay",
    },
    aiModelVersion: {
      type: "string",
      validations: { required: true },
      storageKey: "R3HaSZNLyMHw",
      filterIndex: false,
      searchIndex: false,
    },
    allowedSenders: {
      type: "json",
      default: "[]",
      storageKey: "ZXHQgHHhiMnO",
      filterIndex: false,
      searchIndex: false,
    },
    anthropicApiKey: {
      type: "encryptedString",
      storageKey: "AIWyq2WYvtt2",
    },
    apiRateLimitPerMinute: {
      type: "number",
      default: 60,
      decimals: 0,
      storageKey: "apiRateLimitPerMinute",
    },
    archivedFolder: {
      type: "string",
      validations: { required: true },
      storageKey: "pifJtF0NvayG",
      filterIndex: false,
      searchIndex: false,
    },
    auditLogRetentionDays: {
      type: "number",
      default: 365,
      decimals: 0,
      validations: { required: true },
      storageKey: "Lc3COXMtxf1h",
      filterIndex: false,
      searchIndex: false,
    },
    autoArchiveEnabled: {
      type: "boolean",
      default: true,
      storageKey: "F54dYyUt3Nsj",
      filterIndex: false,
      searchIndex: false,
    },
    autoResolveSimple: {
      type: "boolean",
      default: false,
      storageKey: "autoResolveSimple",
    },
    autoSendConfidenceThreshold: {
      type: "number",
      default: 0.85,
      decimals: 2,
      validations: {
        required: true,
        numberRange: { min: 0, max: 1 },
      },
      storageKey: "gp8xGwVNdp2J",
      filterIndex: false,
      searchIndex: false,
    },
    autoSendGeneralFAQ: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "B0iWcy24WY6Y",
      filterIndex: false,
      searchIndex: false,
    },
    autoSendGlobalEnabled: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "shY45wbfHd09",
      searchIndex: false,
    },
    autoSendMaxPerDay: {
      type: "number",
      default: 50,
      decimals: 0,
      validations: { required: true },
      storageKey: "vNsoHh2ck393",
      filterIndex: false,
      searchIndex: false,
    },
    autoSendOpeningHours: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "C1WyzSozgLSn",
      searchIndex: false,
    },
    autoSendProductInstructions: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "EdoMgxsmfAuk",
    },
    autoSendTodayCount: {
      type: "number",
      default: 0,
      decimals: 0,
      validations: { required: true },
      storageKey: "74ppFr1TlEa4",
      searchIndex: false,
    },
    autoSendTrackingRequests: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "yjc6-YHBCe53",
    },
    autoSuggestResponses: {
      type: "boolean",
      default: true,
      storageKey: "autoSuggestResponses",
    },
    autoTriageEnabled: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "4rl3jBitpcXN",
      filterIndex: false,
      searchIndex: false,
    },
    backupRetentionDays: {
      type: "number",
      default: 30,
      decimals: 0,
      storageKey: "backupRetentionDays",
    },
    backupSchedule: {
      type: "string",
      default: "daily",
      storageKey: "backupSchedule",
    },
    batchSize: {
      type: "number",
      default: 50,
      decimals: 0,
      validations: { required: true },
      storageKey: "8K15dH1EvPpZ",
      filterIndex: false,
      searchIndex: false,
    },
    bulkActionsEnabled: {
      type: "boolean",
      default: true,
      validations: { required: true },
      storageKey: "4sOPPnLJtQAX",
      filterIndex: false,
      searchIndex: false,
    },
    businessHoursFrom: {
      type: "string",
      default: "09:00",
      storageKey: "businessHoursFrom",
    },
    businessHoursTo: {
      type: "string",
      default: "17:00",
      storageKey: "businessHoursTo",
    },
    cacheDurationMinutes: {
      type: "number",
      default: 15,
      decimals: 0,
      storageKey: "cacheDurationMinutes",
    },
    categoryBaseScores: {
      type: "json",
      default:
        '{"refund_cancellation": 10, "delivery_deadline": 10, "complaint": 7, "order_issue": 7, "technical_product_help": 4, "general_question": 1, "presales_question": 2}',
      validations: { required: true },
      storageKey: "Jye_SKlioGxz",
      filterIndex: false,
      searchIndex: false,
    },
    chatgptIntegrationEnabled: {
      type: "boolean",
      default: true,
      validations: { required: true },
      storageKey: "DHr3CaKoMhG8",
      filterIndex: false,
      searchIndex: false,
    },
    classificationProvider: {
      type: "enum",
      default: "openai",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: ["openai", "custom", "rules_based"],
      validations: { required: true },
      storageKey: "8IdPGgfAS0-1",
      searchIndex: false,
    },
    companyName: {
      type: "string",
      validations: { required: true },
      storageKey: "s_KD1SfLFzNp",
    },
    connectedMailbox: { type: "email", storageKey: "_tz2zAbMrlpr" },
    conversationViewEnabled: {
      type: "boolean",
      default: true,
      validations: { required: true },
      storageKey: "wuAf09_b18ve",
      searchIndex: false,
    },
    currency: {
      type: "string",
      default: "gbp",
      storageKey: "currency",
    },
    customerDomains: {
      type: "json",
      storageKey: "6Q97tp5gsc0h",
      filterIndex: false,
      searchIndex: false,
    },
    customerIdentificationRules: {
      type: "json",
      storageKey: "7h4rgt8NnBE2",
      filterIndex: false,
      searchIndex: false,
    },
    customerValueScoring: {
      type: "boolean",
      default: true,
      storageKey: "customerValueScoring",
    },
    dailyDigestEnabled: {
      type: "boolean",
      default: false,
      storageKey: "OjRzr2ZoEt25",
      searchIndex: false,
    },
    dailyDigestTime: {
      type: "string",
      default: "09:00",
      storageKey: "a2pDwnf2X7JZ",
      filterIndex: false,
      searchIndex: false,
    },
    dateFormat: {
      type: "string",
      default: "dmy",
      storageKey: "dateFormat",
    },
    debugModeEnabled: {
      type: "boolean",
      default: false,
      storageKey: "debugModeEnabled",
    },
    defaultDateRangeDays: {
      type: "number",
      default: 7,
      decimals: 0,
      validations: { required: true },
      storageKey: "_cE49l155uyp",
    },
    defaultInboxFolder: {
      type: "string",
      validations: { required: true },
      storageKey: "gznmtRa0mye-",
      filterIndex: false,
      searchIndex: false,
    },
    defaultSignature: {
      type: "string",
      storageKey: "gTAsU1VFbgO3",
      filterIndex: false,
      searchIndex: false,
    },
    deleteArchivedData: {
      type: "boolean",
      default: false,
      storageKey: "jj5YEX7XrkK2",
      filterIndex: false,
      searchIndex: false,
    },
    draftInstructions: { type: "string", storageKey: "aKa320MR85uB" },
    emailNotificationsEnabled: {
      type: "boolean",
      default: false,
      storageKey: "f1zQ5vtzjFbd",
      searchIndex: false,
    },
    excludedSenders: {
      type: "json",
      storageKey: "z3rYngUXPrTt",
      filterIndex: false,
      searchIndex: false,
    },
    focusedInboxOnly: {
      type: "boolean",
      default: true,
      storageKey: "jC0_3_crLV1v",
    },
    graphApiRateLimitDelay: {
      type: "number",
      default: 100,
      decimals: 0,
      validations: { required: true },
      storageKey: "ehen42nI0gPq",
      filterIndex: false,
      searchIndex: false,
    },
    ignoreLastSyncAt: {
      type: "boolean",
      default: true,
      storageKey: "ignoreLastSyncAt",
      filterIndex: false,
      searchIndex: false,
    },
    imapHost: {
      type: "string",
      storageKey: "TE_0xc_zDGT5",
      filterIndex: false,
      searchIndex: false,
    },
    imapPassword: {
      type: "encryptedString",
      storageKey: "I-haSm9LJOUs",
    },
    imapPort: {
      type: "number",
      default: 993,
      decimals: 0,
      storageKey: "h-lPiQJtPPhP",
      filterIndex: false,
      searchIndex: false,
    },
    imapSecure: {
      type: "boolean",
      default: true,
      storageKey: "sJlXLi0dYwBD",
      filterIndex: false,
      searchIndex: false,
    },
    imapUsername: {
      type: "string",
      storageKey: "a8jb3ad2j1Y3",
      filterIndex: false,
      searchIndex: false,
    },
    ipWhitelist: {
      type: "string",
      storageKey: "KqD73mBnDhny",
      filterIndex: false,
      searchIndex: false,
    },
    language: {
      type: "string",
      default: "en",
      storageKey: "language",
    },
    lastBackupAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "lastBackupAt",
    },
    lastDailyDigestAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "lastDailyDigestAt",
    },
    lastSyncAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "CrozLJ3Z-0z2",
      searchIndex: false,
    },
    lazyLoadImages: {
      type: "boolean",
      default: true,
      storageKey: "lazyLoadImages",
    },
    manualReviewQueue: {
      type: "boolean",
      default: true,
      storageKey: "manualReviewQueue",
    },
    maxEmailsPerTriage: {
      type: "number",
      default: 500,
      decimals: 0,
      validations: {
        required: true,
        numberRange: { min: 1, max: 1000 },
      },
      storageKey: "N_5ENft7dU-y",
      filterIndex: false,
      searchIndex: false,
    },
    microsoftAccessToken: {
      type: "encryptedString",
      storageKey: "fhSVKRv4L2wP",
    },
    microsoftClientId: {
      type: "string",
      storageKey: "microsoftClientId",
    },
    microsoftClientSecret: {
      type: "encryptedString",
      storageKey: "microsoftClientSecret",
    },
    microsoftConnectionStatus: {
      type: "string",
      default: "disconnected",
      validations: { regex: ["^(disconnected|connected|error)$"] },
      storageKey: "zMKj6AaFb8dc",
    },
    microsoftLastError: {
      type: "string",
      storageKey: "I_a0_CP6JoTO",
      filterIndex: false,
      searchIndex: false,
    },
    microsoftLastVerifiedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "ws4hq3YxGaQt",
      searchIndex: false,
    },
    microsoftRefreshToken: {
      type: "encryptedString",
      storageKey: "kyYI2LTonh3-",
    },
    microsoftTenantId: {
      type: "string",
      storageKey: "microsoftTenantId",
    },
    microsoftTokenExpiresAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "YfmNF2Q1Rr3k",
      searchIndex: false,
    },
    mondayApiToken: {
      type: "encryptedString",
      storageKey: "WMIGbQhsUbph",
    },
    mondayConnectionStatus: {
      type: "string",
      default: "disconnected",
      validations: { regex: ["^(disconnected|connected|error)$"] },
      storageKey: "1L9I-2G8JRWU",
    },
    mondayLastVerifiedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "noEdVsmzxGZ_",
      searchIndex: false,
    },
    neverAutoSendCategories: {
      type: "json",
      default: '["refund_cancellation","complaint"]',
      validations: { required: true },
      storageKey: "lBTf1NhRdrdy",
      filterIndex: false,
      searchIndex: false,
    },
    notificationEmail: {
      type: "email",
      storageKey: "t0kKLHf9ofQS",
      filterIndex: false,
      searchIndex: false,
    },
    notifyOnAutoSendFailure: {
      type: "boolean",
      default: false,
      storageKey: "JnYPE_zpWxSR",
      searchIndex: false,
    },
    notifyOnCustomerReply: {
      type: "boolean",
      default: false,
      storageKey: "5GfvoxeE3AhY",
      searchIndex: false,
    },
    notifyOnHighPriority: {
      type: "boolean",
      default: false,
      storageKey: "YXJNHrVkgnsZ",
      searchIndex: false,
    },
    notifyOnNewConversation: {
      type: "boolean",
      default: false,
      storageKey: "z-uvaIjJXL_R",
      searchIndex: false,
    },
    notifyOnP0: {
      type: "boolean",
      default: true,
      validations: { required: true },
      storageKey: "tggdvqyR2UsX",
      filterIndex: false,
      searchIndex: false,
    },
    notifyOnP1: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "GYYabK1gGABF",
      filterIndex: false,
      searchIndex: false,
    },
    openaiModel: {
      type: "string",
      validations: { required: true },
      storageKey: "ZqJGEC_1Zafb",
      filterIndex: false,
      searchIndex: false,
    },
    outlookConnected: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "vZXtNCbEmIoY",
      searchIndex: false,
    },
    prefetchLinks: {
      type: "boolean",
      default: true,
      storageKey: "prefetchLinks",
    },
    priorityBandThresholds: {
      type: "json",
      default: '{"P0": 25, "P1": 18, "P2": 10, "P3": 0}',
      validations: { required: true },
      storageKey: "N2YmLxXbouuS",
      filterIndex: false,
      searchIndex: false,
    },
    processUnreadOnly: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "LJMKq7IU_UI6",
      filterIndex: false,
      searchIndex: false,
    },
    productionSchedulerEnabled: {
      type: "boolean",
      default: false,
      storageKey: "productionSchedulerEnabled",
      filterIndex: false,
      searchIndex: false,
    },
    pwRequireExpiry: {
      type: "boolean",
      default: false,
      storageKey: "FmojWuVVvhuu",
    },
    pwRequireMinLength: {
      type: "boolean",
      default: true,
      storageKey: "XXCn1uTC0fZJ",
      filterIndex: false,
      searchIndex: false,
    },
    pwRequireNumbers: {
      type: "boolean",
      default: true,
      storageKey: "YQ0txHMGaXfN",
      filterIndex: false,
      searchIndex: false,
    },
    pwRequireSpecial: {
      type: "boolean",
      default: true,
      storageKey: "2Rie2E6C39M8",
      filterIndex: false,
      searchIndex: false,
    },
    pwRequireUppercase: {
      type: "boolean",
      default: true,
      storageKey: "97oiVQKaB2Lc",
      filterIndex: false,
      searchIndex: false,
    },
    realTimeUpdatesEnabled: {
      type: "boolean",
      default: true,
      storageKey: "realTimeUpdatesEnabled",
    },
    redactAddresses: {
      type: "boolean",
      default: true,
      validations: { required: true },
      storageKey: "hwBsITP5Z6en",
      filterIndex: false,
      searchIndex: false,
    },
    require2FA: {
      type: "boolean",
      default: false,
      storageKey: "3Xwf1AviGkXT",
      filterIndex: false,
      searchIndex: false,
    },
    requireHumanCategories: {
      type: "json",
      default: '["refund_cancellation", "complaint"]',
      validations: { required: true },
      storageKey: "mjad2HLUz8QG",
      searchIndex: false,
    },
    resolvedFolder: {
      type: "string",
      storageKey: "Ct0Ta7Mg1gXv",
      filterIndex: false,
      searchIndex: false,
    },
    retentionDays: {
      type: "number",
      default: 90,
      decimals: 0,
      validations: {
        required: true,
        numberRange: { min: 1, max: null },
      },
      storageKey: "ZTbetaT4aAgb",
      filterIndex: false,
      searchIndex: false,
    },
    riskKeywords: {
      type: "json",
      default:
        '["legal", "lawyer", "chargeback", "court", "lawsuit"]',
      storageKey: "Dmjkrf_s_lgE",
      filterIndex: false,
      searchIndex: false,
    },
    riskScoring: {
      type: "boolean",
      default: true,
      storageKey: "M9mASdB9ZgWS",
    },
    scheduledActionsEnabled: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "oaw2JEP7t8SM",
      filterIndex: false,
      searchIndex: false,
    },
    scoringWeights: {
      type: "json",
      default:
        '{"risk": 5, "time": 4, "sentiment": 4, "blocker": 4, "value": 3, "age": 3, "escalation": 3}',
      validations: { required: true },
      storageKey: "fZITEx7DB5Pq",
      filterIndex: false,
      searchIndex: false,
    },
    sentimentAnalysis: {
      type: "boolean",
      default: true,
      storageKey: "sentimentAnalysis",
    },
    sessionTimeoutMinutes: {
      type: "number",
      default: 30,
      decimals: 0,
      storageKey: "eccooJJRHFxx",
      filterIndex: false,
      searchIndex: false,
    },
    shopifyAccessToken: {
      type: "encryptedString",
      storageKey: "xfwOm1B5C0AA::String-xfwOm1B5C0AA",
    },
    shopifyConnectionStatus: {
      type: "string",
      default: "disconnected",
      validations: { regex: ["^(disconnected|connected|error)$"] },
      storageKey: "z95thshZolpn",
    },
    shopifyLastVerifiedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "3RlxGne3_IWu",
      searchIndex: false,
    },
    shopifyStoreDomain: {
      type: "string",
      storageKey: "44o2kOFCIaEF",
    },
    slaP0: {
      type: "string",
      default: "15min",
      storageKey: "XFiTyhNhJQln",
      searchIndex: false,
    },
    slaP1: {
      type: "string",
      default: "1hr",
      storageKey: "cUUkfperWFGC",
      searchIndex: false,
    },
    slaP2: {
      type: "string",
      default: "4hr",
      storageKey: "V560Npoz2iGl",
      searchIndex: false,
    },
    slaP3: {
      type: "string",
      default: "24hr",
      storageKey: "pJj3OdgJE4DW",
      searchIndex: false,
    },
    smtpFromAddress: {
      type: "email",
      storageKey: "i7cK9kLDrCKr",
      filterIndex: false,
      searchIndex: false,
    },
    smtpHost: {
      type: "string",
      storageKey: "zekloFot_pQF",
      filterIndex: false,
      searchIndex: false,
    },
    smtpPassword: {
      type: "encryptedString",
      storageKey: "Y2GxZj_u9wx-",
    },
    smtpPort: {
      type: "number",
      default: 587,
      decimals: 0,
      storageKey: "yeXueyf_vtOa",
      filterIndex: false,
      searchIndex: false,
    },
    smtpReplyTo: {
      type: "email",
      storageKey: "s8EPl5lYhhnM",
      filterIndex: false,
      searchIndex: false,
    },
    smtpSecure: {
      type: "boolean",
      default: true,
      storageKey: "yEXr3ttBph3Q",
      filterIndex: false,
      searchIndex: false,
    },
    smtpUsername: {
      type: "string",
      storageKey: "HF15I6V_hA-2",
      filterIndex: false,
      searchIndex: false,
    },
    storeFullBodies: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "xbBDbshaUsaD",
      filterIndex: false,
      searchIndex: false,
    },
    supportEmail: { type: "email", storageKey: "TQCpafKxXVYK" },
    supportFolder: { type: "string", storageKey: "JSe1CmrIhdGH" },
    supportHours: {
      type: "string",
      validations: { required: true },
      storageKey: "7ri1x5BP7_HL",
      filterIndex: false,
      searchIndex: false,
    },
    syncEnabled: {
      type: "boolean",
      default: false,
      validations: { required: true },
      storageKey: "bmIBM1nvqEUk",
      filterIndex: false,
      searchIndex: false,
    },
    teamsWebhookUrl: {
      type: "url",
      storageKey: "1z-hHpOlmNAY",
      filterIndex: false,
      searchIndex: false,
    },
    telemetryBannersEnabled: {
      type: "boolean",
      default: true,
      storageKey: "telemetryBannersEnabled",
      filterIndex: false,
      searchIndex: false,
    },
    temperature: {
      type: "number",
      default: 0.7,
      decimals: 2,
      storageKey: "temperature",
    },
    timeSensitivity: {
      type: "boolean",
      default: true,
      storageKey: "timeSensitivity",
    },
    timezone: {
      type: "string",
      default: "gmt",
      storageKey: "timezone",
    },
    triageSchedule: {
      type: "string",
      storageKey: "0qKMelUhIgjD",
      filterIndex: false,
      searchIndex: false,
    },
    workflowBatchProcessing: {
      type: "boolean",
      default: true,
      storageKey: "workflowBatchProcessing",
    },
  },
};
